spring:
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
#  url: jdbc:oracle:thin:@localhost:1521:ORCL
  url: jdbc:mysql://127.0.0.1:3306/xyg
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
#  driver-class-name: oracle.jdbc.driver.OracleDriver
 thymeleaf:
     cache: false
     prefix: classpath:/templates/
     check-template-location: true
     suffix: .html
     encoding: UTF-8
     mode: LEGACYHTML5
#rabbitmq 的基本配置
 rabbitmq:
   host: 127.0.0.1
   port: 5672
   username: root
   password: root
   virtual-host: /order
   publisher-confirms: true
   publisher-returns: true
   template:
     mandatory: true
# 消费端配置
   listener:
     simple:
       acknowledge-mode: manual
       concurrency: 5
       max-concurrency: 10
       prefetch: 1
 application:
   name: hello-service

mybatis:
    type-aliases-package: com.example.demo.entity
    mapper-locations: classpath:mapper/*.xml
server:
  port: 8081

myProp:
 name: myname

#management:
#  endpoint:
#    beans:
#      enabled: true
#    info:
#      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
