
spring:
  datasource:
    url: jdbc:oracle:thin:@szoraqa01.skystartrade.com:1521/sstqa01
    username: skystar
    password: skystar2018
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      pool-name: MyHikariCP
      max-lifetime: 0
      connection-timeout: 30000
  profiles:
    active: dev
#      driver-class-name: oracle.jdbc.pool.OracleDataSource
server:
  port: 4099

mybatis:
    type-aliases-package: com.example.demo.entity
    mapper-locations: classpath:mapper/*.xml
    config-location: classpath:mybatis-config.xml